"""Bitwidth constants for PLATFORM_BMV2."""

STRING_MAX_BITWIDTH = 256

PORT_BITWIDTH = 9
VRF_BITWIDTH = STRING_MAX_BITWIDTH
NEXTHOP_ID_BITWIDTH = STRING_MAX_BITWIDTH
ROUTER_INTERFACE_ID_BITWIDTH = STRING_MAX_BITWIDTH
WCMP_GROUP_ID_BITWIDTH = STRING_MAX_BITWIDTH
MIRROR_SESSION_ID_BITWIDTH = STRING_MAX_BITWIDTH
QOS_QUEUE_BITWIDTH = STRING_MAX_BITWIDTH
TUNNEL_ID_BITWIDTH = STRING_MAX_BITWIDTH

# From fixed/bitwidths.p4 (not overridden by google/bitwidths.p4).
WCMP_SELECTOR_INPUT_BITWIDTH = 16
ROUTE_METADATA_BITWIDTH = 6
ACL_METADATA_BITWIDTH = 8
MULTICAST_GROUP_ID_BITWIDTH = 16
REPLICA_INSTANCE_BITWIDTH = 16
